<ol id="global-menu">
    <li>Speisekarte</li>
    <li>Veranstaltung</li>
    <li>Login</li>
    <li>Storno</li>
    <li class="my-sonic">Festbon</li>
</ol>

<nav id="menu-categories">
    <ol>
        <li class="active" data-key="product">
            <span class="food-category-name">Einzeln</span>
        </li>
        <li data-key="menu">
            <span class="food-category-name">Menü</span>
        </li>
    </ol>
</nav>

<section class="menu-items">
    <ol class="menu-item-listing">

    </ol>
</section>